# /etc/zsh/zlogin ou ~/.zlogin
# (C) Formation Debian GNU/Linux iby Alexis de Lattre
# http://formation-debian.via.ecp.fr/
# modified by louen - louen at palouf.org


# Commands auto-executed when opening a console
# Only run for interactive shells
if [[ -o interactive ]]; then
    uname -a
    uptime
    # Enables messages
    mesg y
fi

