# /etc/zsh/zshenv ou ~/.zshenv
# Fichier de configuration de zsh
# (C) Formation Debian GNU/Linux by Alexis de Lattre
# http://formation-debian.via.ecp.fr/
# modified by louen : louen -at- palouf.org

# Default environnement variables.

# Path configuration. Does NOT includes the current dir.
export DEFAULT_PATH="/usr/local/bin:/usr/local/sbin:/bin:/usr/bin:/usr/sbin:/sbin:$HOME/bin:$HOME/.local/bin"

# On MacOS, add brew binaries to path
if [[ -d "/opt/homebrew/" ]]; then
    export DEFAULT_PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$DEFAULT_PATH"
fi

# By default, we do not inherit the PATH from the parent process and start a new shell with a clean PATH
# However, when running processes out of a conda environment, we need the shell to inherit PATH

if [[ -z "${CONDA_DEFAULT_ENV}" ]]; then
    export PATH=$DEFAULT_PATH
else
    export PATH="$PATH:$DEFAULT_PATH"
fi



# Vim is our default text editor
export VISUAL=vim
export EDITOR=vim

# Permissions rw-r--r-- for creted files
# et rwxr-xr-x for directories
umask 022

