# /etc/zsh/zlogout ou ~/.zlogout
# Fichier de configuration de zsh
# (C) Formation Debian GNU/Linux iby Alexis de Lattre
# http://formation-debian.via.ecp.fr/

# Execute command when logging out a console

# Clears the screen
clear
