" /etc/vim/vimrc ou ~/.vimrc
" Fichier de configuration de Vim
" Formation Debian GNU/Linux par Alexis de Lattre
" http://formation-debian.via.ecp.fr/

" No beep, just flashes
set vb

" Enable syntax hilight
syntax on
" Use a colorscheme for gvim and another for normal vim
if has('gui_running')
    colorscheme solarized
else
    colorscheme delek
endif

" Display the cursor's position (line, column) in the status line
set ruler
" Displays the status line
set laststatus=2
" What's displayed in the status line
set statusline=%<%f%h%m%r%=%l,%c\ %P

" Text wrapping (0 for no wrapping)
set textwidth=0

" Key mappings
" # wraps text at 72 (useful for mail writing)
map # gwap
" wraps texts at 72 and justify
map @ {v}! par 72j

" Do not force old vi retrocompatibility
set nocompatible
" Column number (maybe useless)
"set columns=80

" History size
set history=50
" ~/.viminfo options
set viminfo='20,\"50
" Enables backspace
set backspace=2
" Allow to use the left/right arrow keys to switch line up or down when at the end
set whichwrap=<,>,[,]
" Keeps one line visible above the cursor
set scrolloff=1
" Show the typed commands
set showcmd
" Show matchin delimiters
set showmatch
" Try to keep the same column when moving up or down
set nostartofline
" Command autocomplete mode
set wildmode=list:full
" Do keep indentation when opening a new line
set autoindent
filetype plugin indent on

" C  options
"set cinoptions=(0

" Color terminal options
if &term =~ "xterm-debian" || &term =~ "xterm-xfree86"
    set t_Co=16
    set t_Sf=[3%dm
    set t_Sb=[4%dm
endif

" Never use real tabs but just spaces
set expandtab

" One tab is 4 spaces
set tabstop=4
set softtabstop=4
set shiftwidth=4

" See whitespace
"set list
"set listchars=tab:>-,trail:-

" Searches are case insensitives
set ignorecase

" Use indentation to form folds
set foldmethod=indent
" Folds can go up to 12 indentation levels
set foldlevel=12

" Enable inccremental search
set incsearch
" Highlight the searched pattern
"set hlsearch

" Display line numbers
set number

" Gvim configuration (can also go in .gvimrc)
set guifont=Ubuntu\ Mono\ 12


" Command function and maps
function NumberToggle()
    if(&relativenumber == 1)
        set norelativenumber
    else
        set relativenumber
    endif
endfunc

" Maps control+n to change between relative and absolute line number
nmap <C-n> :call NumberToggle() <CR>


" Use pathogen
"execute pathogen#infect()

" maps for IDE like panel display (needs plugins tagbar and cmake bar)
"nmap <F8> :TagbarToggle<CR>
"nmap <F9> :CMakeBar<CR>

