# /etc/zsh/zlogin ou ~/.zlogin
# (C) Formation Debian GNU/Linux iby Alexis de Lattre
# http://formation-debian.via.ecp.fr/
# modified by louen - louen at palouf.org


# Commands auto-executed when opening a console 

# Dsplays system info 
# figlet -f slant `hostname`
uname -a
uptime
# Enables messages 

mesg y

# Enables 'setum' when using a real console 
#case "`tty`" in /dev/tty[1-6]*)
#    setleds +num
#esac
